### PR TITLE
ZStandard: Use flags from absl

### PR DESCRIPTION
**Pull request by oshogbo**
I'm not sure how this change happened as in my code it was pointing to the right header.

We can't use here the one from sapi as there is a conflict in the headers:

```
[9/10] Building CXX object example/CMakeFiles/sapi_minizstd.dir/main.cc.o
In file included from _deps/absl-src/absl/flags/internal/parse.h:23,
                 from _deps/absl-src/absl/flags/parse.h:29,
                 from /home/oshogbo/sapi-zstd/contrib/zstd/sandboxed.h:25,
                 from ../example/main.cc:24:
_deps/absl-src/absl/flags/declare.h:63: warning: "ABSL_DECLARE_FLAG" redefined
   63 | #define ABSL_DECLARE_FLAG(type, name)                        \
      | 
In file included from /home/oshogbo/sapi-zstd/contrib/zstd/sandboxed.h:24,
                 from ../example/main.cc:24:
/home/oshogbo/sapi-zstd/sandboxed_api/util/flag.h:23: note: this is the location of the previous definition
   23 | #define ABSL_DECLARE_FLAG(type, name) DECLARE_##type(name)
      | 
```

---
This change is [Reviewable](https://reviewable.io/reviews/google/sandboxed-api/107)

### CODE REVIEW

**Review by okunz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @okunz and @oshogbo)

___
*[contrib/zstd/sandboxed.h, line 24 at r1](https://reviewable.io/reviews/google/sandboxed-api/107#-MuznqO60x_W9sPdpkrw:-MuznqO60x_W9sPdpkrx:b-n78ykb) ([raw file](https://github.com/google/sandboxed-api/blob/fa08080f0637f77f7b16924336319f8940617678/contrib/zstd/sandboxed.h#L24)):*
> ```objc
> 
> #include "sapi_zstd.sapi.h"  // NOLINT(build/include)
> #include "absl/flags/flag.h"
> ```

Looks like it can be removed all together.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @okunz)

___
*[contrib/zstd/sandboxed.h, line 24 at r1](https://reviewable.io/reviews/google/sandboxed-api/107#-MuznqO60x_W9sPdpkrw:-Muzs_UF2soBFH_K370_:b82zuor) ([raw file](https://github.com/google/sandboxed-api/blob/fa08080f0637f77f7b16924336319f8940617678/contrib/zstd/sandboxed.h#L24)):*
<details><summary><i>Previously, okunz (Oliver Kunz) wrote…</i></summary><blockquote>

Looks like it can be removed all together.
</blockquote></details>

Actually it can't as it defines absl::GetFlag which is required.

**Review by okunz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @okunz and @oshogbo)

___
*[contrib/zstd/sandboxed.h, line 24 at r1](https://reviewable.io/reviews/google/sandboxed-api/107#-MuznqO60x_W9sPdpkrw:-MuzvOwM-BGZrPzGcjVw:b9mdt3o) ([raw file](https://github.com/google/sandboxed-api/blob/fa08080f0637f77f7b16924336319f8940617678/contrib/zstd/sandboxed.h#L24)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Actually it can't as it defines absl::GetFlag which is required.
</blockquote></details>

This header file doesn't use absl::Flags, I'm assuming you're referring to example/main.cc:60?

Google's C++ style doesn't rely on transitive inclusions, see https://google.github.io/styleguide/cppguide.html#Include_What_You_Use

**Review by cblichmann — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/107)* status: all files reviewed, 1 unresolved discussion (waiting on @okunz)

___
*[contrib/zstd/sandboxed.h, line 24 at r1](https://reviewable.io/reviews/google/sandboxed-api/107#-MuznqO60x_W9sPdpkrw:-Mv-RSf8BhMMcJVVgduU:bvm8emy) ([raw file](https://github.com/google/sandboxed-api/blob/fa08080f0637f77f7b16924336319f8940617678/contrib/zstd/sandboxed.h#L24)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I mean I'm happy to move it but in different PR I was asked to move it here:
https://reviewable.io/reviews/google/sandboxed-api/100#-MutldPd4TWOT713MUEz
</blockquote></details>

That's not what I meant, actually. I just meant to move the include order _within_ the file, not to move the includes to "a file above" (in Reviewable.io order).

Sorry for that, I should have been more clear.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/107)* status: all files reviewed, 1 unresolved discussion (waiting on @okunz)

___
*[contrib/zstd/sandboxed.h, line 24 at r1](https://reviewable.io/reviews/google/sandboxed-api/107#-MuznqO60x_W9sPdpkrw:-Mv-W2802eK0ItX9OvTo:b-2njnd2) ([raw file](https://github.com/google/sandboxed-api/blob/fa08080f0637f77f7b16924336319f8940617678/contrib/zstd/sandboxed.h#L24)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

That's not what I meant, actually. I just meant to move the include order _within_ the file, not to move the includes to "a file above" (in Reviewable.io order).

Sorry for that, I should have been more clear.
</blockquote></details>

Ou I see :(

Sorry for that, I will fix that in all reviews.

**Review by okunz — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Review by okunz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/107#-:-Mv2QT853oYMHQZn8eAH:bg7igk9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Pull request merged**
