### PR TITLE
Sandbox zopfli

### PR DESCRIPTION
**Pull request by oshogbo**
This change is [Reviewable](https://reviewable.io/reviews/google/sandboxed-api/100)

### CODE REVIEW

**Review by cblichmann — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/100)* status: all files reviewed, 6 unresolved discussions (waiting on @oshogbo)

___
*[contrib/zopfli/CMakeLists.txt, line 36 at r1](https://reviewable.io/reviews/google/sandboxed-api/100#-MuRCC0A2MoFQqt7KwKs:-MuRCC0A2MoFQqt7KwKt:br6iklc) ([raw file](https://github.com/google/sandboxed-api/blob/36ab000db659d5e1d9a2398d12825bd2476ff943/contrib/zopfli/CMakeLists.txt#L36)):*
> ```CMake
>   "${SAPI_ROOT}"
>   "${CMAKE_BINARY_DIR}/sandboxed-api-build"
>   EXCLUDE_FROM_ALL
> ```

Can you please move this to above `FetchContent_Declare()` and remove the `include()`? SAPI then provides `FetchContent_Declare()` and `FetchContent_MakeAvailable()`



_Code quote:_
```CMake
add_subdirectory(
  "${SAPI_ROOT}"
  "${CMAKE_BINARY_DIR}/sandboxed-api-build"
  EXCLUDE_FROM_ALL
)
```
___
*[contrib/zopfli/sandboxed.h, line 20 at r1](https://reviewable.io/reviews/google/sandboxed-api/100#-MuRC_Nm6celRtBaffhZ:-MuRC_Nm6celRtBaffh_:b-2ehef5) ([raw file](https://github.com/google/sandboxed-api/blob/36ab000db659d5e1d9a2398d12825bd2476ff943/contrib/zopfli/sandboxed.h#L20)):*
> ```objc
> #include <libgen.h>
> #include <syscall.h>
> ```

Please also include `memory`
___
*[contrib/zopfli/example/main.cc, line 30 at r1](https://reviewable.io/reviews/google/sandboxed-api/100#-MuRCi9y9QBQUtjaCYHF:-MuRCi9y9QBQUtjaCYHG:b-o1gntl) ([raw file](https://github.com/google/sandboxed-api/blob/36ab000db659d5e1d9a2398d12825bd2476ff943/contrib/zopfli/example/main.cc#L30)):*
> ```cpp
>   std::string prog_name(argv[0]);
>   google::InitGoogleLogging(argv[0]);
>   gflags::ParseCommandLineFlags(&argc, &argv, true);
> ```

This should be calling `absl::ParseCommandLine(argc, argv);`. It returns any non-flag arguments as an `std::vector<>`
___
*[contrib/zopfli/example/main.cc, line 65 at r1](https://reviewable.io/reviews/google/sandboxed-api/100#-MuRDjkL7h_hBJbH4AgR:-MuRDjkL7h_hBJbH4AgS:b6eppka) ([raw file](https://github.com/google/sandboxed-api/blob/36ab000db659d5e1d9a2398d12825bd2476ff943/contrib/zopfli/example/main.cc#L65)):*
> ```cpp
>   absl::Status status = CompressStream(api, infile, outfile, format);
>   if (!status.ok()) {
>     std::cerr << "Unable to compress file.\n";
> ```

We should log the Sandbox failure here



_Code quote:_
```cpp
e.\n";
```
___
*[contrib/zopfli/test/CMakeLists.txt, line 32 at r1](https://reviewable.io/reviews/google/sandboxed-api/100#-MuRDseZ-vSkt28XimVs:-MuRDseZ-vSkt28XimVt:bqaquet) ([raw file](https://github.com/google/sandboxed-api/blob/36ab000db659d5e1d9a2398d12825bd2476ff943/contrib/zopfli/test/CMakeLists.txt#L32)):*
> ```CMake
>   sapi::temp_file
>   gtest
>   gtest_main
> ```

Replace this (and `sapi::sapi` with `sapi::test_main`



_Code quote:_
```CMake
  gtest
  gtest_main
  gmock
```
___
*[contrib/zopfli/test/zopfli_test.cc, line 45 at r1](https://reviewable.io/reviews/google/sandboxed-api/100#-MuREM6i1Fy4u2xQSS_z:-MuREM6i1Fy4u2xQSSa-:bk9o3mg) ([raw file](https://github.com/google/sandboxed-api/blob/36ab000db659d5e1d9a2398d12825bd2476ff943/contrib/zopfli/test/zopfli_test.cc#L45)):*
> ```cpp
> #define NAME DEFLATE
> #define METHOD ZOPFLI_FORMAT_DEFLATE
> #include "zopfli_template.c"
> ```

Please don't use this macro magic. Instead, we should implement this as a value parameterized test (https://github.com/google/googletest/blob/main/docs/advanced.md#value-parameterized-tests).



_Code quote:_
```cpp
#define NAME DEFLATE
#define METHOD ZOPFLI_FORMAT_DEFLATE
#include "zopfli_template.c"
#undef NAME
#undef METHOD
```

**Review by cblichmann — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 6 of 8 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/100)* status: all files reviewed, 3 unresolved discussions (waiting on @oshogbo)

___
*[contrib/zopfli/sandboxed.h, line 35 at r4](https://reviewable.io/reviews/google/sandboxed-api/100#-MutmSFp3XUlSF91uKoY:-MutmSFp3XUlSF91uKoZ:b90u770) ([raw file](https://github.com/google/sandboxed-api/blob/e901852f8123c28f922857fca90c4079c8a2be1b/contrib/zopfli/sandboxed.h#L35)):*
> ```objc
>         .AllowMmap()
>         .AllowSystemMalloc()
>         .DangerDefaultAllowAll()
> ```

I overlooked this, we do not want that :)



_Code quote:_
```objc
.DangerDefaultAllowAll()
```
___
*[contrib/zopfli/example/main.cc, line 15 at r4](https://reviewable.io/reviews/google/sandboxed-api/100#-MutldPd4TWOT713MUEz:-MutldPd4TWOT713MUF-:b-29fm63) ([raw file](https://github.com/google/sandboxed-api/blob/e901852f8123c28f922857fca90c4079c8a2be1b/contrib/zopfli/example/main.cc#L15)):*
> ```cpp
> // limitations under the License.
> 
> #include <absl/flags/flag.h>
> ```

These should be quoted includes and be moved to above `../sandboxed.h`



_Code quote:_
```cpp
#include <absl/flags/flag.h>
#include <absl/flags/parse.h>
```
___
*[contrib/zopfli/test/zopfli_test.cc, line 52 at r4](https://reviewable.io/reviews/google/sandboxed-api/100#-Mutm-E-93pB9U3OJo7U:-Mutm-E-93pB9U3OJo7V:b-iejtxw) ([raw file](https://github.com/google/sandboxed-api/blob/e901852f8123c28f922857fca90c4079c8a2be1b/contrib/zopfli/test/zopfli_test.cc#L52)):*
> ```cpp
>   std::string infile_s = GetTestFilePath("text");
>   std::string outfile_s = GetTemporaryFile("text.out");
>   ASSERT_FALSE(outfile_s.empty());
> ```

Optional: Alternative spelling: `ASSERT_THAT(outfile_s, Not(IsEmpty()));`

**Review by cblichmann — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/100)* status: all files reviewed, 2 unresolved discussions (waiting on @oshogbo)

___
*[contrib/zopfli/CMakeLists.txt, line 22 at r5](https://reviewable.io/reviews/google/sandboxed-api/100#-Mv-OqNV3WYUJm0B6iNB:-Mv-OqNV3WYUJm0B6iNC:b-am22wd) ([raw file](https://github.com/google/sandboxed-api/blob/e112b2e98e17c801a241db82eb2bc8f50a5e82f8/contrib/zopfli/CMakeLists.txt#L22)):*
> ```CMake
> set(CMAKE_CXX_STANDARD_REQUIRED True)
> 
> set(SAPI_ROOT "" CACHE PATH "Path to the Sandboxed API source tree")
> ```

Can you please apply the same change I did for jsonnet here as well?
https://github.com/google/sandboxed-api/blob/main/contrib/jsonnet/CMakeLists.txt#L21

Also please add an alias library `sapi_contrib:::zopfli`.

That should make it easier for me to later run tests for all contrib sandboxes.



_Code quote:_
```CMake
set(SAPI_ROOT "" CACHE PATH "Path to the Sandboxed API source tree")

add_subdirectory(
  "${SAPI_ROOT}"
  "${CMAKE_BINARY_DIR}/sandboxed-api-build"
  EXCLUDE_FROM_ALL
)
```
___
*[contrib/zopfli/test/zopfli_test.cc, line 26 at r5](https://reviewable.io/reviews/google/sandboxed-api/100#-Mv-O_1eBi5rmbwGd6uY:-Mv-O_1eBi5rmbwGd6uZ:b-is3nhl) ([raw file](https://github.com/google/sandboxed-api/blob/e112b2e98e17c801a241db82eb2bc8f50a5e82f8/contrib/zopfli/test/zopfli_test.cc#L26)):*
> ```cpp
> 
> using ::sapi::IsOk;
> using ::testing::IsEmpty;
> ```

Probably should add a using decl for `::testing::Not` as well.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/100)* status: all files reviewed, 2 unresolved discussions (waiting on @cblichmann)

___
*[contrib/zopfli/CMakeLists.txt, line 22 at r5](https://reviewable.io/reviews/google/sandboxed-api/100#-Mv-OqNV3WYUJm0B6iNB:-Mv-epwu9vsDuCvGuQP2:b-tvy2k6) ([raw file](https://github.com/google/sandboxed-api/blob/e112b2e98e17c801a241db82eb2bc8f50a5e82f8/contrib/zopfli/CMakeLists.txt#L22)):*
> sapi_contrib:::zopfli
Fixed.
___
*[contrib/zopfli/sandboxed.h, line 35 at r4](https://reviewable.io/reviews/google/sandboxed-api/100#-MutmSFp3XUlSF91uKoY:-MutrBhe-e8NWswcLVOP:bbb3pfu) ([raw file](https://github.com/google/sandboxed-api/blob/e901852f8123c28f922857fca90c4079c8a2be1b/contrib/zopfli/sandboxed.h#L35)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

I overlooked this, we do not want that :)
</blockquote></details>

Oh, I overlooked this as well.
Supposed to be only for tests...
___
*[contrib/zopfli/example/main.cc, line 15 at r4](https://reviewable.io/reviews/google/sandboxed-api/100#-MutldPd4TWOT713MUEz:-Muu5GLlAL9Yw_41T9qu:bt2vr1b) ([raw file](https://github.com/google/sandboxed-api/blob/e901852f8123c28f922857fca90c4079c8a2be1b/contrib/zopfli/example/main.cc#L15)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

These should be quoted includes and be moved to above `../sandboxed.h`
</blockquote></details>

Fixed.
___
*[contrib/zopfli/test/zopfli_test.cc, line 52 at r4](https://reviewable.io/reviews/google/sandboxed-api/100#-Mutm-E-93pB9U3OJo7U:-Muu5HQf9TGRj_-jKYLo:brgq1k0) ([raw file](https://github.com/google/sandboxed-api/blob/e901852f8123c28f922857fca90c4079c8a2be1b/contrib/zopfli/test/zopfli_test.cc#L52)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Optional: Alternative spelling: `ASSERT_THAT(outfile_s, Not(IsEmpty()));`
</blockquote></details>

Sure. Done.
___
*[contrib/zopfli/test/zopfli_test.cc, line 26 at r5](https://reviewable.io/reviews/google/sandboxed-api/100#-Mv-O_1eBi5rmbwGd6uY:-Mv-faF04yCQIcJPN6w9:b3rg9ga) ([raw file](https://github.com/google/sandboxed-api/blob/e112b2e98e17c801a241db82eb2bc8f50a5e82f8/contrib/zopfli/test/zopfli_test.cc#L26)):*
> ::testing::Not
Fixed.

**Review by cblichmann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/100)* status: all files reviewed, 2 unresolved discussions (waiting on @cblichmann and @oshogbo)

___
*[contrib/zopfli/CMakeLists.txt, line 22 at r5](https://reviewable.io/reviews/google/sandboxed-api/100#-Mv-OqNV3WYUJm0B6iNB:-Mv3-Lxt9ggV5cZ8xCo7:b-wwb1db) ([raw file](https://github.com/google/sandboxed-api/blob/e112b2e98e17c801a241db82eb2bc8f50a5e82f8/contrib/zopfli/CMakeLists.txt#L22)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

> sapi_contrib:::zopfli
Fixed.
</blockquote></details>

I don't see any such change. Did you push? Or is Reviewable hiding this for some reason?

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/100)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @cblichmann)

___
*[contrib/zopfli/CMakeLists.txt, line 22 at r5](https://reviewable.io/reviews/google/sandboxed-api/100#-Mv-OqNV3WYUJm0B6iNB:-Mv381MIE4KwBYswUa3P:b-zedsxz) ([raw file](https://github.com/google/sandboxed-api/blob/e112b2e98e17c801a241db82eb2bc8f50a5e82f8/contrib/zopfli/CMakeLists.txt#L22)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

I don't see any such change. Did you push? Or is Reviewable hiding this for some reason?
</blockquote></details>

It's on me.

**Review by cblichmann — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Review by okunz — APPROVED** [review]
> Reviewed 2 of 8 files at r3, 1 of 2 files at r4, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Review by cblichmann — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Pull request merged**
