### PR TITLE
Sandbox LibRaw

### PR DESCRIPTION
**Pull request by piotrbartman**
This change is [Reviewable](https://reviewable.io/reviews/google/sandboxed-api/161)

### CODE REVIEW

**Review by DemiMarie — COMMENTED** [review]
Since libraw is considered untrusted, any data returned from it should be sanitized, or at least not used insecurely by the example code.

**Review by cblichmann — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 5 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/161)* status: 7 of 11 files reviewed, 14 unresolved discussions (waiting on @cblichmann and @piotrbartman)

___
*[contrib/libraw/CMakeLists.txt, line 39 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVPrXX3rI4omQ8ANp_:-MzVPrXX3rI4omQ8ANpa:bn3gtjs) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/CMakeLists.txt#L39)):*
> ```CMake
> )
> FetchContent_GetProperties(libraw)
> FetchContent_Populate(libraw)
> ```

We can use `FetchContent_MakeAvailable` here as well. It should fetch the `libraw_SOURCE_DIR` property, too.



_Code quote:_
```CMake
FetchContent_GetProperties(libraw)
FetchContent_Populate(libraw)
```
___
*[contrib/libraw/raw.gen.h.in, line 14 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVQ7t82SMIv1ysRwOu:-MzVQ7t82SMIv1ysRwOv:b-65hrnr) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/raw.gen.h.in#L14)):*
> ```
> // See the License for the specific language governing permissions and
> // limitations under the License.
> ```

This header should have an include guard, even if it is just simply adding `#defines` for `uint64_t`.

I'd also add `#inclucde <cstdint>` to ensure `uint64_t` is available.
___
*[contrib/libraw/sandboxed.h, line 48 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVQWRP6lJkQj2D0tp8:-MzVQWRP6lJkQj2D0tp9:bvfesyv) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/sandboxed.h#L48)):*
> ```objc
> };
> 
> #endif  // CONTRIB_LIBRAW_SANDBOXED_
> ```

Please remove trailing whitespace. Also, the comment should be `CONTRIB_LIBRAW_SANDBOXED_H_` (missing the `H_` part).
___
*[contrib/libraw/example/main.cc, line 23 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVQsaP0-0VMosmoFQV:-MzVQsaP0-0VMosmoFQW:bxn7qe9) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/example/main.cc#L23)):*
> ```cpp
> #include "contrib/libraw/utils/utils_libraw.h"
> 
> void usage(const char* av) {
> ```

This should be named `Usage` or `PrintUsage`.
See https://google.github.io/styleguide/cppguide.html#Function_Names
___
*[contrib/libraw/example/main.cc, line 34 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVRC3O-cmJANqq9JsY:-MzVRC3O-cmJANqq9JsZ:b-9f1ctg) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/example/main.cc#L34)):*
> ```cpp
> }
> 
> unsigned subtract_bl(int val, int bl) { return val > bl ? val - bl : 0; }
> ```

- Use standard integer types (see https://google.github.io/styleguide/cppguide.html#Integer_Types) instead of plain `unsigned`
- Name should be `SubtractBl`or `SubtractBlack`
___
*[contrib/libraw/example/main.cc, line 36 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVRXaQAmlv8vJorMjI:-MzVRXaR3M1OCO0JrmsU:bumqdne) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/example/main.cc#L36)):*
> ```cpp
> unsigned subtract_bl(int val, int bl) { return val > bl ? val - bl : 0; }
> 
> int main(int ac, char* av[]) {
> ```

These are non-standard names. Prefer to call them `argc` and `argv`



_Code quote:_
```cpp
int ac, char* av[]
```
___
*[contrib/libraw/example/main.cc, line 41 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVRcbX4zK4lo1olCsy:-MzVRcbX4zK4lo1olCsz:b-xoods5) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/example/main.cc#L41)):*
> ```cpp
>   if (ac < 4) {
>     usage(av[0]);
>     exit(1);
> ```

In the `main()` function, prefer just to use `return` instead of `exit`. Use `EXIT_SUCCESS` and `EXIT_FAILURE` to indicate status.
___
*[contrib/libraw/example/main.cc, line 60 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVRo5j7onkk7iNdqzF:-MzVRo5j7onkk7iNdqzG:blpaxti) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/example/main.cc#L60)):*
> ```cpp
>   LibRawSapiSandbox sandbox(file_name.GetData());
>   if (!sandbox.Init().ok()) {
>     std::cerr << "Unable to start sandbox\n";
> ```

I'd be good to log the sandbox error.

```c++
if (absl::Status status = sandbox.Init(); !status.ok()) {
  std::cerr << "Unable to start sandbox: " << status.message() << "\n";
  return EXIT_FAILURE;
}
```
___
*[contrib/libraw/example/main.cc, line 67 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVSq4B1yGro14WBdfd:-MzVSq4B1yGro14WBdfe:bz7bual) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/example/main.cc#L67)):*
> ```cpp
> 
>   LibRaw lr(&sandbox, av[1]);
>   if (not lr.CheckIsInit().ok()) {
> ```

Do not use C++ alternative tokens for operators, just use unary`!`.



_Code quote:_
```cpp
not
```
___
*[contrib/libraw/example/main.cc, line 128 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVSzog6yqDuJHB7LK_:-MzVSzog6yqDuJHB7LKa:b9e42ew) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/example/main.cc#L128)):*
> ```cpp
>   for (int row = rowstart;
>        row < rowstart + height && row < *raw_height;
>        row++) {
> ```

Prefer the more canonical pre-increment: `++row`



_Code quote:_
```cpp
row++
```
___
*[contrib/libraw/example/main.cc, line 163 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVT5ZM6fp4g7R9vJd4:-MzVT5ZM6fp4g7R9vJd5:b-xcx2nq) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/example/main.cc#L163)):*
> ```cpp
> 
>   return EXIT_SUCCESS;
> }
> ```

Remove trailing whitespace
___
*[contrib/libraw/test/libraw_test.cc, line 31 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVTBfj00XzQrSYYy3p:-MzVTBfj00XzQrSYYy3q:bkacwyh) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/test/libraw_test.cc#L31)):*
> ```cpp
>   int COLOR[4][4];
>   int color_values[4][4];
> } TestData[] = {
> ```

Constants should be named like this: `kTestData`
___
*[contrib/libraw/test/libraw_test.cc, line 183 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVTLuE7CQUXrIE8PBN:-MzVTLuE7CQUXrIE8PBO:b-xcx2nq) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/test/libraw_test.cc#L183)):*
> ```cpp
>                          testing::ValuesIn(TestData));
> 
> }  // namespace
> ```

Remove trailing whitespace
___
*[contrib/libraw/utils/utils_libraw.h, line 80 at r2](https://reviewable.io/reviews/google/sandboxed-api/161#-MzVTOtlE5YYLKHkT-2v:-MzVTOtlE5YYLKHkT-2w:b-xcx2nq) ([raw file](https://github.com/google/sandboxed-api/blob/1b1c085cfec926af5bc1cfc85c10a0ca6f89d143/contrib/libraw/utils/utils_libraw.h#L80)):*
> ```objc
> };
> 
> #endif  // CONTRIB_LIBRAW_UTILS_UTILS_LIBRAW_H_
> ```

Remove trailing whitespace

**Review by cblichmann — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 3 of 8 files at r2, 4 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/161)* status: 8 of 11 files reviewed, 17 unresolved discussions (waiting on @cblichmann and @piotrbartman)

___
*[contrib/libraw/example/main.cc, line 4 at r3](https://reviewable.io/reviews/google/sandboxed-api/161#-MznQriU7YzT4IUkUkrn:-MznQriU7YzT4IUkUkro:bvy88ww) ([raw file](https://github.com/google/sandboxed-api/blob/7e76425c37f6c3e1aa75dd1b811ac89865ecee28/contrib/libraw/example/main.cc#L4)):*
> ```cpp
> //
> // Licensed under the Apache License, Version 2.0 (the "License");
> // you may !use this file except in compliance with the License.
> ```

Please revert this one :)
___
*[contrib/libraw/example/main.cc, line 34 at r3](https://reviewable.io/reviews/google/sandboxed-api/161#-MznQwRp0c6mRoSOcr9d:-MznQwRp0c6mRoSOcr9e:b-synzfu) ([raw file](https://github.com/google/sandboxed-api/blob/7e76425c37f6c3e1aa75dd1b811ac89865ecee28/contrib/libraw/example/main.cc#L34)):*
> ```cpp
> }
> 
> uint16_t SubtractBlack(uint16_t val, unsigned int bl) {
> ```

`bl` should also use `uint16_t`



_Code quote:_
```cpp
unsigned int
```
___
*[contrib/libraw/example/main.cc, line 144 at r3](https://reviewable.io/reviews/google/sandboxed-api/161#-MzYyK_HE06RbrNXV7Wc:-MzYyK_HE06RbrNXV7Wd:bhd85ih) ([raw file](https://github.com/google/sandboxed-api/blob/7e76425c37f6c3e1aa75dd1b811ac89865ecee28/contrib/libraw/example/main.cc#L144)):*
> ```cpp
> 
>       if (rcolors[col % 48] == channel) {
>         absl::StatusOr<unsigned int> cblack = lr.GetCBlack(channel);
> ```

Please use `uint16_t` (that's what `GetCBlack()` basically returns, right?)



_Code quote:_
```cpp
unsigned int
```

**Comment by piotrbartman** [comment]
> _[contrib/libraw/example/main.cc, line 144 at r3](https://reviewable.io/reviews/google/sandboxed-api/161#-MzYyK_HE06RbrNXV7Wc:-MzYyK_HE06RbrNXV7Wd:bhd85ih) ([raw file](https://github.com/google/sandboxed-api/blob/7e76425c37f6c3e1aa75dd1b811ac89865ecee28/contrib/libraw/example/main.cc#L144)):_
> 
> > ```c++
> >       if (rcolors[col % 48] == channel) {
> >         absl::StatusOr<unsigned int> cblack = lr.GetCBlack(channel);
> > ```
> 
> Please use `uint16_t` (that's what `GetCBlack()` basically returns, right?)
> 
> _Code quote:_
> 
> ```c++
> unsigned int
> ```

`GetCBlack()` returns a single value from `unsigned` array generated in the structure in `sapi_libraw.sapi.h`, so it returns `unsigned`. For this reason, I used `unsigned int` here.

**Review by cblichmann — COMMENTED** [review]
> Reviewed 3 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/161)* status: all files reviewed, 17 unresolved discussions (waiting on @piotrbartman)

___
*[contrib/libraw/example/main.cc, line 144 at r3](https://reviewable.io/reviews/google/sandboxed-api/161#-MzYyK_HE06RbrNXV7Wc:-MzoNx9w79yEv7vyxJy-:b-7aitaz) ([raw file](https://github.com/google/sandboxed-api/blob/7e76425c37f6c3e1aa75dd1b811ac89865ecee28/contrib/libraw/example/main.cc#L144)):*
<details><summary><i>Previously, piotrbartman wrote…</i></summary><blockquote>

`GetCBlack()` returns a single value from `unsigned` array generated in the structure in `sapi_libraw.sapi.h`, so it returns `unsigned`. For this reason, I used `unsigned int` here.
</blockquote></details>

Thanks for clarifying.

**Comment by cblichmann** [comment]
LGTM pending internal review.

**Pull request closed without merging**
