### PR TITLE
Sandbox hunspell

### PR DESCRIPTION
**Pull request by oshogbo**
This change is [Reviewable](https://reviewable.io/reviews/google/sandboxed-api/103)

### CODE REVIEW

**Comment by okunz** [comment]
___
*[contrib/hunspell/CMakeLists.txt, line 7 at r1](https://reviewable.io/reviews/google/sandboxed-api/103#-MujEUIOB5iERJTq2Fo9:-MujEUIOB5iERJTq2FoA:box7nqz) ([raw file](https://github.com/google/sandboxed-api/blob/243e40d4b1116cc47342acb31a049a85dc9f5cff/contrib/hunspell/CMakeLists.txt#L7)):*
> ```CMake
> # You may obtain a copy of the License at
> #
> #     http://www.apache.org/licenses/LICENSE-2.0
> ```

Please, replace with https (also in the other files)



_Code quote:_
```CMake
http
```

**Comment by oshogbo** [comment]
___
*[contrib/hunspell/CMakeLists.txt, line 7 at r1](https://reviewable.io/reviews/google/sandboxed-api/103#-MujEUIOB5iERJTq2Fo9:-MujYbgZ3uqU_RD2kZbA:b-xf5juv) ([raw file](https://github.com/google/sandboxed-api/blob/243e40d4b1116cc47342acb31a049a85dc9f5cff/contrib/hunspell/CMakeLists.txt#L7)):*
<details><summary><i>Previously, okunz (Oliver Kunz) wrote…</i></summary><blockquote>

Please, replace with https (also in the other files)
</blockquote></details>

Thanks fixed in all PRs.

**Review by cblichmann — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/103)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @cblichmann, @okunz, and @oshogbo)

___
*[contrib/hunspell/CMakeLists.txt, line 33 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoJ5PrDJ22pPc0HARi:-MuoJ5PrDJ22pPc0HARj:bkdd6es) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/CMakeLists.txt#L33)):*
> ```CMake
> 
> FetchContent_GetProperties(libhunspell)
> if (NOT libhunspell_POPULATED)
> ```

In CMake, `if()` is a command, so we don't use a space between `if` and the opening parenthesis.
___
*[contrib/hunspell/CMakeLists.txt, line 51 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoJskp9NoYZ98Bgt5n:-MuoJskp9NoYZ98Bgt5o:bv0ebw5) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/CMakeLists.txt#L51)):*
> ```CMake
>     message("-- Running ./configure for libhunspell...")
>     execute_process(
>       COMMAND ./configure
> ```

Optional: `execute_process()` supports running multiple `COMMAND`s, so we could roll the `autoreconf` call into this one.



_Code quote:_
```CMake
COMMAND ./configure
```
___
*[contrib/hunspell/CMakeLists.txt, line 101 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoIpZfAyOQopiY36FT:-MuoIpZgAYZXAbvWSrif:bl9tgyy) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/CMakeLists.txt#L101)):*
> ```CMake
> add_subdirectory(
>   "${SAPI_ROOT}"
>   "${CMAKE_BINARY_DIR}/sandboxed-api-build"
> ```

Please move this to the top, right after the `set(SAPI_ROOT...`. You can then also remove the `include(FetchContent)`, as SAPI does this already.



_Code quote:_
```CMake
add_subdirectory(
  "${SAPI_ROOT}"
  "${CMAKE_BINARY_DIR}/sandboxed-api-build"
  EXCLUDE_FROM_ALL
)
```
___
*[contrib/hunspell/sandboxed.h, line 33 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoKBdEApnOXj_hYP64:-MuoKBdEApnOXj_hYP65:b-rar7my) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/sandboxed.h#L33)):*
> ```objc
>  private:
>   std::unique_ptr<sandbox2::Policy> ModifyPolicy(
>       sandbox2::PolicyBuilder *) override {
> ```

Please keep `*` and `&` to the left.



_Code quote:_
```objc
 *
```
___
*[contrib/hunspell/example/main.cc, line 23 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoKSuY15LZSP46yNnW:-MuoKSuY15LZSP46yNnX:b-dqojx) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/example/main.cc#L23)):*
> ```cpp
> #include "../sandboxed.h"
> 
> absl::Status PrintSuggest(HunspellApi &api, sapi::v::RemotePtr &hunspellrp,
> ```

See my comment in the other file -- keep `&` and `*` close to the type.
Note that the Google C++ style allows both, but for SAPI we have made this choice (codified in `.clang-format` in the project root).



_Code quote:_
```cpp
 &
```
___
*[contrib/hunspell/example/main.cc, line 46 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoKtGm6UCugfHQx2U7:-MuoKtGm6UCugfHQx2U8:b-oll48u) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/example/main.cc#L46)):*
> ```cpp
>     SAPI_ASSIGN_OR_RETURN(std::string sugestion,
>                           api.GetSandbox()->GetCString(sugrp));
>     std::cout << sugestion[i] << std::endl;
> ```

Note that this flushes the stream on every line. We probably want to just use `"\n"` here.



_Code quote:_
```cpp
std::endl
```

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/103)* status: 7 of 11 files reviewed, 7 unresolved discussions (waiting on @cblichmann and @okunz)

___
*[contrib/hunspell/CMakeLists.txt, line 33 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoJ5PrDJ22pPc0HARi:-MuoXKLsAxmnnXKTIiDu:bt2vr1b) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/CMakeLists.txt#L33)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

In CMake, `if()` is a command, so we don't use a space between `if` and the opening parenthesis.
</blockquote></details>

Fixed.
___
*[contrib/hunspell/CMakeLists.txt, line 51 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoJskp9NoYZ98Bgt5n:-MuoXjpk8Lb2TCJ20w8X:b594da3) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/CMakeLists.txt#L51)):*
> include(FetchContent),
Fixed.
___
*[contrib/hunspell/CMakeLists.txt, line 101 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoIpZfAyOQopiY36FT:-MuoXlz70mcj6Qx9Bla7:b-87x74f) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/CMakeLists.txt#L101)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Please move this to the top, right after the `set(SAPI_ROOT...`. You can then also remove the `include(FetchContent)`, as SAPI does this already.
</blockquote></details>

Fxied
___
*[contrib/hunspell/sandboxed.h, line 33 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoKBdEApnOXj_hYP64:-MuoXnBXDPWctpXa6HQE:btav34t) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/sandboxed.h#L33)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Please keep `*` and `&` to the left.
</blockquote></details>

Fxied.
___
*[contrib/hunspell/example/main.cc, line 23 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoKSuY15LZSP46yNnW:-MuoXvaq6qh33pMPfb7y:b-d5q2ho) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/example/main.cc#L23)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

See my comment in the other file -- keep `&` and `*` close to the type.
Note that the Google C++ style allows both, but for SAPI we have made this choice (codified in `.clang-format` in the project root).
</blockquote></details>

Fixed. Thanks.
___
*[contrib/hunspell/example/main.cc, line 46 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoKtGm6UCugfHQx2U7:-MuoY506C6g59ZzmjDK6:bt2vr1b) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/example/main.cc#L46)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Note that this flushes the stream on every line. We probably want to just use `"\n"` here.
</blockquote></details>

Fixed.

**Review by okunz — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/103)* status: 7 of 11 files reviewed, 10 unresolved discussions (waiting on @cblichmann, @okunz, and @oshogbo)

___
*[contrib/hunspell/CMakeLists.txt, line 33 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoJ5PrDJ22pPc0HARi:-Mup01-a5K7etFqCdMaA:b-ils0lt) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/CMakeLists.txt#L33)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

There are other occurrences of if() that should get addressed as well. 
___
*[contrib/hunspell/example/main.cc, line 82 at r3](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoqObm2ptOq87F1OgP:-MuoqObm2ptOq87F1OgQ:b-z7h10g) ([raw file](https://github.com/google/sandboxed-api/blob/41aa55b900bcfe4bd73f172363bdd789ead308b0/contrib/hunspell/example/main.cc#L82)):*
> ```cpp
>   sapi::v::RemotePtr hunspellrp(*hunspell);
> 
>   std::ifstream wtclst(argv[3], std::ios_base::in);
> ```

This name wasn't very descriptive for me, I had to check what argv3 is. How about word_to_check_list?

see https://google.github.io/styleguide/cppguide.html#General_Naming_Rules



_Code quote:_
```cpp
wtclst
```
___
*[contrib/hunspell/example/main.cc, line 91 at r3](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoqsupESEskSr3kTbX:-MuoqsuqB4ThAhek0-YF:b-o9rwpm) ([raw file](https://github.com/google/sandboxed-api/blob/41aa55b900bcfe4bd73f172363bdd789ead308b0/contrib/hunspell/example/main.cc#L91)):*
> ```cpp
>   while (std::getline(wtclst, buf)) {
>     sapi::v::ConstCStr cbuf(buf.c_str());
>     absl::StatusOr<int> rdp = api.Hunspell_spell(&hunspellrp, cbuf.PtrBefore());
> ```

Same as above. I would suggest to just use result as variable name.
___
*[contrib/hunspell/test/hunspell_test.cc, line 28 at r3](https://reviewable.io/reviews/google/sandboxed-api/103#-Muor7Z3D7YFWamxC8oo:-Muor7Z3D7YFWamxC8op:bo7qgxn) ([raw file](https://github.com/google/sandboxed-api/blob/41aa55b900bcfe4bd73f172363bdd789ead308b0/contrib/hunspell/test/hunspell_test.cc#L28)):*
> ```cpp
> class HunspellTest : public ::testing::Test {
>  protected:
>   static constexpr char encoding_[] = "UTF-8";
> ```

Variables declared with constexpr or const should be named with a leading k (see https://google.github.io/styleguide/cppguide.html#General_Naming_Rules)

I believe you can also replace char with absl::string_view.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/103)* status: 7 of 11 files reviewed, 10 unresolved discussions (waiting on @cblichmann and @okunz)

___
*[contrib/hunspell/example/main.cc, line 82 at r3](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoqObm2ptOq87F1OgP:-Mup5jDk-gUwZ1RpEwRU:bv1502h) ([raw file](https://github.com/google/sandboxed-api/blob/41aa55b900bcfe4bd73f172363bdd789ead308b0/contrib/hunspell/example/main.cc#L82)):*
> word_to_check_list
Fixed.
___
*[contrib/hunspell/example/main.cc, line 91 at r3](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoqsupESEskSr3kTbX:-Mup63n5416fay_XrNOz:bt2vr1b) ([raw file](https://github.com/google/sandboxed-api/blob/41aa55b900bcfe4bd73f172363bdd789ead308b0/contrib/hunspell/example/main.cc#L91)):*
<details><summary><i>Previously, okunz (Oliver Kunz) wrote…</i></summary><blockquote>

Same as above. I would suggest to just use result as variable name.
</blockquote></details>

Fixed.
___
*[contrib/hunspell/test/hunspell_test.cc, line 28 at r3](https://reviewable.io/reviews/google/sandboxed-api/103#-Muor7Z3D7YFWamxC8oo:-Mup9l19BBgrx0szF6Xo:bt2vr1b) ([raw file](https://github.com/google/sandboxed-api/blob/41aa55b900bcfe4bd73f172363bdd789ead308b0/contrib/hunspell/test/hunspell_test.cc#L28)):*
<details><summary><i>Previously, okunz (Oliver Kunz) wrote…</i></summary><blockquote>

Variables declared with constexpr or const should be named with a leading k (see https://google.github.io/styleguide/cppguide.html#General_Naming_Rules)

I believe you can also replace char with absl::string_view.
</blockquote></details>

Fixed.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/103)* status: all files reviewed, 7 unresolved discussions (waiting on @cblichmann and @okunz)

___
*[contrib/hunspell/CMakeLists.txt, line 33 at r2](https://reviewable.io/reviews/google/sandboxed-api/103#-MuoJ5PrDJ22pPc0HARi:-Mv-gFNL8GH3CTZzFR40:bt2vr1b) ([raw file](https://github.com/google/sandboxed-api/blob/0346fc36f9ed713ebf7de7910e1eaa19150dbbea/contrib/hunspell/CMakeLists.txt#L33)):*
<details><summary><i>Previously, okunz (Oliver Kunz) wrote…</i></summary><blockquote>

There are other occurrences of if() that should get addressed as well. 
</blockquote></details>

Fixed.
___
*[contrib/hunspell/CMakeLists.txt, line 48 at r7](https://reviewable.io/reviews/google/sandboxed-api/103#-Mv-PlGs1_FYZ6A9vWE3:-Mv-jjtPCr14tqCk9PGw:buurvub) ([raw file](https://github.com/google/sandboxed-api/blob/5fab71a044bf6c268a420421a956ee2ee27f1247/contrib/hunspell/CMakeLists.txt#L48)):*
> --disable-documentatio
I don't see option for disabling documentation.
___
*[contrib/hunspell/CMakeLists.txt, line 50 at r7](https://reviewable.io/reviews/google/sandboxed-api/103#-Mv-Q1D_CMSEcceh3k0L:-Mv-h4AYESmsfa54fzlA:b-lbdz18) ([raw file](https://github.com/google/sandboxed-api/blob/5fab71a044bf6c268a420421a956ee2ee27f1247/contrib/hunspell/CMakeLists.txt#L50)):*
> libhunspell_config_result
Fixed.
___
*[contrib/hunspell/test/hunspell_test.cc, line 53 at r7](https://reviewable.io/reviews/google/sandboxed-api/103#-Mv-QpSsDqYWhoHT_cXC:-Mv-k-A1AuEQgHnoD3R_:bt2vr1b) ([raw file](https://github.com/google/sandboxed-api/blob/5fab71a044bf6c268a420421a956ee2ee27f1247/contrib/hunspell/test/hunspell_test.cc#L53)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Keep left close to the type.
</blockquote></details>

Fixed.

**Review by cblichmann — COMMENTED** [review]
> Reviewed 4 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/103)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @cblichmann and @okunz)

**Pull request merged**
